build:
  image: fracting/msys32-docker
  commands:
    - wine --version

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667
