debug: true

build:
  image: fracting/msys32-docker:local
  shell: $$custom-shell
  commands:
    - echo $$custom-shell
    - echo $MSYSTEM
    - if [ $$custom-shell = msys32 ]; then pacman -S --noconfirm --needed libiconv-devel gettext-devel; fi
    - if [ $$custom-shell = mingw32 ]; then pacman -S --noconfirm --needed mingw-w64-i686-pkg-config; fi
    - ./autogen.sh
    - ./configure
    - make
    - make check

build:
  image: fracting/msys32-docker:local
  shell: sh
  commands:
    - echo haha dummy test.


notify:
  irc:
    prefix: build
    nick: xz
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

matrix:
  custom-shell:
    - msys32
    - mingw32
