build:
    # image: bradrydzewski/gcc:4.8
  image: gcc:4.8
  environment:
    - DEBIAN_FRONTEND=noninteractive
  commands:
    - ls
    - echo $HOME
    - echo $DRONE_BUILD_DIR
    - pwd
    - stat `pwd`
    - sudo apt-get update -y
    - sudo apt-get install -y autopoint
    - sudo mkdir testsudodir
    - sudo touch testsudotouch
    - touch testtouch
    - mkdir testdir
    - ./autogen.sh
    - ./configure
    - make
    - make test
