debug: true

build:
  image: fracting/msys32-docker:local
  shell: $$shell-path
  commands:
    - echo $$shell-path
    - if [ $$shell-path = msys32 ]; then pacman -S --noconfirm --needed libiconv-devel gettext-devel; fi
    - if [ $$shell-path = mingw32 ]; then pacman -S --noconfirm --needed mingw-w64-i686-pkg-config; fi
    - ./autogen.sh
    - ./configure
    - make
    - make check

notify:
  irc:
    prefix: build
    nick: xz
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

matrix:
  shell-path:
    - msys32
    - mingw32
