build:
  image: fracting/msys32
  shell: msys32
  commands:
    - if [ $$platform = msys32 ]; then pacman -S --noconfirm --needed libiconv-devel gettext-devel; fi
    - if [ $$platform = mingw32 ]; then pacman -S --noconfirm --needed mingw-w64-i686-pkg-config; fi
    - ./autogen.sh
    - ./configure
    - make
    - make check

notify:
  irc:
    prefix: build
    nick: xz
    channel: msys2
    server:
      host: irc.oftc.net
      port: 6667

matrix:
  platform:
    - msys32
    - mingw32
