build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - pacman -S --noconfirm mingw-w64-$$target-pkg-config
    - ./configure
    - make
    - make check

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  include:
    - arch: 64
      target: x86_64
    - arch: 32
      target: i686
