debug: true

build:
  image: fracting/msys32-docker:latest
  shell: ALLOC_XVFB=true /usr/bin/msys2-shell
  commands:
    - uname -a
    - ls -lh
    - pwd

notify:
  irc:
    prefix: build
    nick: xz
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

