# Build configuration for https://tea-ci.org
# Tea CI is a fork of Drone CI with Msys2 support
# Feel free to share Tea CI to more open source developers
# http://docs.tea-ci.org/usage/overview/
# Please add your project to https://github.com/TeaCI/tea-ci/wiki/Msys2-on-Wine#use-msys2-in-tea-ci

debug: true
build:
  image: teaci/cygwin$$arch
  pull: true
  shell: cygwin$$arch
  commands:
# Workaround docker image limitation
# These packages can't be preinstalled inside docker image because docker image does not support cygwin symlink.
    - WINEDEBUG=-all c:/cygwin-installer.exe --site http://mirrors.tea-ci.org/cygwin --local-package-dir Z:/tmp/cygwin -W -P autoconf,automake -q &> /dev/null

    - ./autogen.sh
    - ./configure
    - make
    - make check

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  arch:
    - 64
    - 32
