# Build configuration for https://tea-ci.org
# Tea CI is a fork of Drone CI with Msys2 support
# Feel free to share Tea CI to more open source developers
# http://docs.tea-ci.org/usage/overview/
# Please add your project to https://github.com/TeaCI/tea-ci/wiki/Msys2-on-Wine#use-msys2-in-tea-ci

debug: true
build:
  image: teaci/cygwin$$arch
  pull: true
  shell: /bin/sh
  commands:
    - ./autogen.sh
    - make
    - make check

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  arch:
    - 64
    - 32
