build:
  image: fracting/msys32-docker:latest
  commands:
    - uname -a

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

