build:
  image: bradrydzewski/gcc:4.8
  environment:
    - DEBIAN_FRONTEND=noninteractive
  commands:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update -y
    - sudo apt-get install -y autopoint
    - mkdir testdir
    - ./autogen.sh
    - ./configure
    - make
    - make test
