build:
  image: teaci/msys32
  shell: msys32
  commands:
    - pacman -S --noconfirm mingw-w64-cross-crt-git

notify:
  irc:
    prefix: build
    nick: xz
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
