# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  environment:
    - WINEDEBUG=relay,tid
    - DEBUG_WRAPPER=true
  commands:
    - cmd /c dir
    - cmd /c "echo %WINDIR%"
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config
    - ./autogen.sh
    - ./configure
    - make
    - make check

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  arch:
    - 64
    - 32
