debug: true

build:
  image: fracting/msys32-docker:latest
  shell: /usr/bin/msys2-shell
  commands:
    - uname -a

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667
