build:
  image: fracting/msys32-docker
  commands:
    - wine --version
    - ls ~/.wine
    - ALLOC_XVFB=true msys2-shell -c "hello drone"

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667
