# Build configure for https://www.tea-ci.org (fork of Drone CI with Msys2 support)
build:
  image: ubuntu:16.04
  pull: true
  commands:
    - apt-get install -y strace
    - ls
    - strace ls

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

matrix:
  arch:
    - 64
    - 32
