build:
  image: fracting/msys32-docker:local
  shell: $$custom-shell
  commands:
    - echo $$custom-shell
    - echo $MSYSTEM
    - echo $$testval
    - if [ $$custom-shell = sh ]; then apt-get update -y; apt-get install build-essential; apt-get build-dep xz-utils; fi
    - if [ $$custom-shell = msys32 ]; then pacman -S --noconfirm --needed libiconv-devel gettext-devel; fi
    - if [ $$custom-shell = mingw32 ]; then pacman -S --noconfirm --needed mingw-w64-i686-pkg-config; fi
    - ./autogen.sh
    - ./configure
    - make
    - make check

notify:
  irc:
    prefix: build
    nick: xz
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

matrix:
    - custom-shell: sh
      testval: haha1
    - custom-shell: msys32
      testval: haha2
    - custom-shell: mingw32
