debug: true

build:
  image: fracting/msys32-docker:local
  shell: $$shell-path
  commands:
    - pacman -S --noconfirm --needed libiconv-devel gettext-devel
    - ./autogen.sh
    - ./configure
    - make
    - make check

notify:
  irc:
    prefix: build
    nick: xz
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

matrix:
  shell-path:
    - /usr/bin/msys2-shell
    - msys2-shell
