build:
  image: fracting/msys32-docker:testhub
  commands:
    - wine --version
    - ls ~/.wine
    - . /etc/msys2-env
    - mkdir -p ${MSYS_ROOT}/`dirname ${DRONE_BUILD_DIR}`
    - ln -sv ${DRONE_BUILD_DIR} ${MSYS_ROOT}/${DRONE_BUILD_DIR}
    - ALLOC_XVFB=true msys2-shell -c "cd ${DRONE_BUILD_DIR}; ls; pacman -S --needed --noconfirm gettext; ./autogen.sh"

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667
