os:
  - linux

env:
  - WINEARCH=win32
  - WINEARCH=""

cache: apt

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x16"

before_script:
  - sudo add-apt-repository -y ppa:pipelight/daily
  - sudo apt-get update -qq
  - sudo apt-get install -y --install-recommends wine-staging wine-staging-compat subversion
  - MSYS2_SCRIPTS_DEB=msys2-scripts_20150801_i386.deb
  - wget https://github.com/fracting/msys2-scripts-deb/raw/master/${MSYS2_SCRIPTS_DEB}
  - sudo dpkg -i ${MSYS2_SCRIPTS_DEB}

language: c

compiler:
  - gcc

script:
  - srcdir=~/src
  - subdir=xz
  - pkgbuild_repo=https://github.com/fracting/MINGW-packages/trunk/mingw-w64-xz-git
  - svn co ${pkgbuild_repo} ${srcdir}
  - ln -svf ${PWD} ${srcdir}/${subdir}
  - cp ${srcdir}/PKGBUILD ~
  - msys2-prepare
  - msys2-wrapper "pacman -S --needed --noconfirm mingw-w64-i686-toolchain"
  - msys2-wrapper "makepkg-mingw -s -f --noconfirm --noextract --skippgpcheck"
